# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\daq_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from QPlot import QPlot

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pulseOutput = QPlot(self.centralwidget)
        self.pulseOutput.setGeometry(QtCore.QRect(11, 11, 479, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulseOutput.sizePolicy().hasHeightForWidth())
        self.pulseOutput.setSizePolicy(sizePolicy)
        self.pulseOutput.setObjectName("pulseOutput")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 70, 190, 210))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.return_pulse_duration_label = QtWidgets.QLabel(self.layoutWidget)
        self.return_pulse_duration_label.setObjectName("return_pulse_duration_label")
        self.gridLayout.addWidget(self.return_pulse_duration_label, 4, 0, 1, 1)
        self.pulse_frequency_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_frequency_label.setObjectName("pulse_frequency_label")
        self.gridLayout.addWidget(self.pulse_frequency_label, 0, 0, 1, 1)
        self.pulse_frequency_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pulse_frequency_spin.setDecimals(3)
        self.pulse_frequency_spin.setMinimum(0.1)
        self.pulse_frequency_spin.setProperty("value", 34.0)
        self.pulse_frequency_spin.setObjectName("pulse_frequency_spin")
        self.gridLayout.addWidget(self.pulse_frequency_spin, 0, 1, 1, 1)
        self.pulse_duration_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_duration_label.setObjectName("pulse_duration_label")
        self.gridLayout.addWidget(self.pulse_duration_label, 1, 0, 1, 1)
        self.pulse_duration_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pulse_duration_spin.setDecimals(1)
        self.pulse_duration_spin.setMinimum(1.0)
        self.pulse_duration_spin.setObjectName("pulse_duration_spin")
        self.gridLayout.addWidget(self.pulse_duration_spin, 1, 1, 1, 1)
        self.pulse_density_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_density_label.setObjectName("pulse_density_label")
        self.gridLayout.addWidget(self.pulse_density_label, 2, 0, 1, 1)
        self.pulse_density_spin = QtWidgets.QSpinBox(self.layoutWidget)
        self.pulse_density_spin.setPrefix("")
        self.pulse_density_spin.setMinimum(1)
        self.pulse_density_spin.setMaximum(1000)
        self.pulse_density_spin.setProperty("value", 20)
        self.pulse_density_spin.setObjectName("pulse_density_spin")
        self.gridLayout.addWidget(self.pulse_density_spin, 2, 1, 1, 1)
        self.pulse_amplitude_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_amplitude_label.setObjectName("pulse_amplitude_label")
        self.gridLayout.addWidget(self.pulse_amplitude_label, 3, 0, 1, 1)
        self.pulse_amplitude_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pulse_amplitude_spin.setDecimals(1)
        self.pulse_amplitude_spin.setMinimum(0.1)
        self.pulse_amplitude_spin.setMaximum(10.0)
        self.pulse_amplitude_spin.setProperty("value", 0.7)
        self.pulse_amplitude_spin.setObjectName("pulse_amplitude_spin")
        self.gridLayout.addWidget(self.pulse_amplitude_spin, 3, 1, 1, 1)
        self.pulse_button = QtWidgets.QPushButton(self.layoutWidget)
        self.pulse_button.setObjectName("pulse_button")
        self.gridLayout.addWidget(self.pulse_button, 7, 0, 1, 2)
        self.return_pulse_duration_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.return_pulse_duration_spin.setDecimals(0)
        self.return_pulse_duration_spin.setMinimum(1.0)
        self.return_pulse_duration_spin.setMaximum(1000.0)
        self.return_pulse_duration_spin.setProperty("value", 100.0)
        self.return_pulse_duration_spin.setObjectName("return_pulse_duration_spin")
        self.gridLayout.addWidget(self.return_pulse_duration_spin, 4, 1, 1, 1)
        self.decimating_factor_spinbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.decimating_factor_spinbox.setMaximum(50)
        self.decimating_factor_spinbox.setProperty("value", 10)
        self.decimating_factor_spinbox.setObjectName("decimating_factor_spinbox")
        self.gridLayout.addWidget(self.decimating_factor_spinbox, 5, 1, 1, 1)
        self.decimating_factor_label = QtWidgets.QLabel(self.layoutWidget)
        self.decimating_factor_label.setObjectName("decimating_factor_label")
        self.gridLayout.addWidget(self.decimating_factor_label, 5, 0, 1, 1)
        self.export_fid_button = QtWidgets.QPushButton(self.layoutWidget)
        self.export_fid_button.setObjectName("export_fid_button")
        self.gridLayout.addWidget(self.export_fid_button, 8, 0, 1, 2)
        self.fidOutput = QPlot(self.centralwidget,xlabel="Time / ms",ylabel="Signal / mV")
        self.fidOutput.setGeometry(QtCore.QRect(10, 200, 481, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fidOutput.sizePolicy().hasHeightForWidth())
        self.fidOutput.setSizePolicy(sizePolicy)
        self.fidOutput.setObjectName("fidOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pulse_button.autoDefault = True
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NMR Control"))
        self.return_pulse_duration_label.setText(_translate("MainWindow", "Read Duration"))
        self.pulse_frequency_label.setText(_translate("MainWindow", "Pulse Freq."))
        self.pulse_frequency_spin.setSuffix(_translate("MainWindow", " kHz"))
        self.pulse_duration_label.setText(_translate("MainWindow", "Pulse Duration"))
        self.pulse_duration_spin.setSuffix(_translate("MainWindow", " ms"))
        self.pulse_density_label.setText(_translate("MainWindow", "Pulse Density"))
        self.pulse_density_spin.setSuffix(_translate("MainWindow", " per pulse"))
        self.pulse_amplitude_label.setText(_translate("MainWindow", "Pulse Amplitude"))
        self.pulse_amplitude_spin.setSuffix(_translate("MainWindow", " V"))
        self.pulse_button.setText(_translate("MainWindow", "Pulse"))
        self.return_pulse_duration_spin.setSuffix(_translate("MainWindow", " ms"))
        self.decimating_factor_label.setText(_translate("MainWindow", "Decimating Factor"))
        self.export_fid_button.setText(_translate("MainWindow", "Export FID"))

