# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\daq_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tabs.setGeometry(QtCore.QRect(10, 10, 771, 501))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.main_tabs.setPalette(palette)
        self.main_tabs.setObjectName("main_tabs")
        self.nmr_signaller_tab = QtWidgets.QWidget()
        self.nmr_signaller_tab.setObjectName("nmr_signaller_tab")
        self.layoutWidget = QtWidgets.QWidget(self.nmr_signaller_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(560, 110, 195, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.export_fid_button = QtWidgets.QPushButton(self.layoutWidget)
        self.export_fid_button.setObjectName("export_fid_button")
        self.gridLayout.addWidget(self.export_fid_button, 7, 0, 1, 2)
        self.pulse_frequency_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_frequency_label.setObjectName("pulse_frequency_label")
        self.gridLayout.addWidget(self.pulse_frequency_label, 0, 0, 1, 1)
        self.pulse_frequency_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pulse_frequency_spin.setDecimals(3)
        self.pulse_frequency_spin.setMinimum(0.1)
        self.pulse_frequency_spin.setProperty("value", 34.0)
        self.pulse_frequency_spin.setObjectName("pulse_frequency_spin")
        self.gridLayout.addWidget(self.pulse_frequency_spin, 0, 1, 1, 1)
        self.pulse_duration_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_duration_label.setObjectName("pulse_duration_label")
        self.gridLayout.addWidget(self.pulse_duration_label, 1, 0, 1, 1)
        self.pulse_duration_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pulse_duration_spin.setDecimals(1)
        self.pulse_duration_spin.setMinimum(1.0)
        self.pulse_duration_spin.setObjectName("pulse_duration_spin")
        self.gridLayout.addWidget(self.pulse_duration_spin, 1, 1, 1, 1)
        self.pulse_density_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_density_label.setObjectName("pulse_density_label")
        self.gridLayout.addWidget(self.pulse_density_label, 2, 0, 1, 1)
        self.pulse_density_spin = QtWidgets.QSpinBox(self.layoutWidget)
        self.pulse_density_spin.setPrefix("")
        self.pulse_density_spin.setMinimum(1)
        self.pulse_density_spin.setMaximum(1000)
        self.pulse_density_spin.setProperty("value", 20)
        self.pulse_density_spin.setObjectName("pulse_density_spin")
        self.gridLayout.addWidget(self.pulse_density_spin, 2, 1, 1, 1)
        self.pulse_amplitude_label = QtWidgets.QLabel(self.layoutWidget)
        self.pulse_amplitude_label.setObjectName("pulse_amplitude_label")
        self.gridLayout.addWidget(self.pulse_amplitude_label, 3, 0, 1, 1)
        self.pulse_amplitude_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pulse_amplitude_spin.setDecimals(1)
        self.pulse_amplitude_spin.setMinimum(0.1)
        self.pulse_amplitude_spin.setMaximum(10.0)
        self.pulse_amplitude_spin.setProperty("value", 0.7)
        self.pulse_amplitude_spin.setObjectName("pulse_amplitude_spin")
        self.gridLayout.addWidget(self.pulse_amplitude_spin, 3, 1, 1, 1)
        self.pulse_button = QtWidgets.QPushButton(self.layoutWidget)
        self.pulse_button.setObjectName("pulse_button")
        self.gridLayout.addWidget(self.pulse_button, 6, 0, 1, 2)
        self.return_pulse_duration_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.return_pulse_duration_spin.setDecimals(0)
        self.return_pulse_duration_spin.setMinimum(1.0)
        self.return_pulse_duration_spin.setMaximum(1000.0)
        self.return_pulse_duration_spin.setProperty("value", 100.0)
        self.return_pulse_duration_spin.setObjectName("return_pulse_duration_spin")
        self.gridLayout.addWidget(self.return_pulse_duration_spin, 4, 1, 1, 1)
        self.return_pulse_duration_label = QtWidgets.QLabel(self.layoutWidget)
        self.return_pulse_duration_label.setObjectName("return_pulse_duration_label")
        self.gridLayout.addWidget(self.return_pulse_duration_label, 4, 0, 1, 1)
        self.decimation_factor_label = QtWidgets.QLabel(self.layoutWidget)
        self.decimation_factor_label.setObjectName("decimation_factor_label")
        self.gridLayout.addWidget(self.decimation_factor_label, 5, 0, 1, 1)
        self.decimation_factor_spin = QtWidgets.QSpinBox(self.layoutWidget)
        self.decimation_factor_spin.setMinimum(1)
        self.decimation_factor_spin.setProperty("value", 1)
        self.decimation_factor_spin.setObjectName("decimation_factor_spin")
        self.gridLayout.addWidget(self.decimation_factor_spin, 5, 1, 1, 1)
        self.pulseOutput = QtWidgets.QWidget(self.nmr_signaller_tab)
        self.pulseOutput.setGeometry(QtCore.QRect(10, 250, 531, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulseOutput.sizePolicy().hasHeightForWidth())
        self.pulseOutput.setSizePolicy(sizePolicy)
        self.pulseOutput.setObjectName("pulseOutput")
        self.fidOutput = QtWidgets.QWidget(self.nmr_signaller_tab)
        self.fidOutput.setGeometry(QtCore.QRect(10, 20, 531, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fidOutput.sizePolicy().hasHeightForWidth())
        self.fidOutput.setSizePolicy(sizePolicy)
        self.fidOutput.setObjectName("fidOutput")
        self.main_tabs.addTab(self.nmr_signaller_tab, "")
        self.fitting_tab = QtWidgets.QWidget()
        self.fitting_tab.setObjectName("fitting_tab")
        self.fid_fitting_plot = QtWidgets.QWidget(self.fitting_tab)
        self.fid_fitting_plot.setGeometry(QtCore.QRect(10, 10, 741, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fid_fitting_plot.sizePolicy().hasHeightForWidth())
        self.fid_fitting_plot.setSizePolicy(sizePolicy)
        self.fid_fitting_plot.setObjectName("fid_fitting_plot")
        self.groupBox = QtWidgets.QGroupBox(self.fitting_tab)
        self.groupBox.setGeometry(QtCore.QRect(9, 329, 431, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 421, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frequency_bound_label = QtWidgets.QLabel(self.layoutWidget1)
        self.frequency_bound_label.setObjectName("frequency_bound_label")
        self.gridLayout_2.addWidget(self.frequency_bound_label, 0, 3, 1, 1)
        self.vpp_bound_upper = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.vpp_bound_upper.setMaximum(200.0)
        self.vpp_bound_upper.setSingleStep(0.01)
        self.vpp_bound_upper.setProperty("value", 200.0)
        self.vpp_bound_upper.setObjectName("vpp_bound_upper")
        self.gridLayout_2.addWidget(self.vpp_bound_upper, 2, 1, 1, 1)
        self.upper_bounds_label = QtWidgets.QLabel(self.layoutWidget1)
        self.upper_bounds_label.setObjectName("upper_bounds_label")
        self.gridLayout_2.addWidget(self.upper_bounds_label, 2, 0, 1, 1)
        self.lower_bounds_label = QtWidgets.QLabel(self.layoutWidget1)
        self.lower_bounds_label.setObjectName("lower_bounds_label")
        self.gridLayout_2.addWidget(self.lower_bounds_label, 1, 0, 1, 1)
        self.vpp_bound_label = QtWidgets.QLabel(self.layoutWidget1)
        self.vpp_bound_label.setObjectName("vpp_bound_label")
        self.gridLayout_2.addWidget(self.vpp_bound_label, 0, 1, 1, 1)
        self.vpp_bound_lower = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.vpp_bound_lower.setPrefix("")
        self.vpp_bound_lower.setMaximum(200.0)
        self.vpp_bound_lower.setSingleStep(0.01)
        self.vpp_bound_lower.setObjectName("vpp_bound_lower")
        self.gridLayout_2.addWidget(self.vpp_bound_lower, 1, 1, 1, 1)
        self.decay_time_bound_label = QtWidgets.QLabel(self.layoutWidget1)
        self.decay_time_bound_label.setObjectName("decay_time_bound_label")
        self.gridLayout_2.addWidget(self.decay_time_bound_label, 0, 2, 1, 1)
        self.constant_bound_lower = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.constant_bound_lower.setMaximum(0.2)
        self.constant_bound_lower.setSingleStep(0.01)
        self.constant_bound_lower.setObjectName("constant_bound_lower")
        self.gridLayout_2.addWidget(self.constant_bound_lower, 1, 4, 1, 1)
        self.frequency_bound_lower = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.frequency_bound_lower.setMaximum(1000.0)
        self.frequency_bound_lower.setObjectName("frequency_bound_lower")
        self.gridLayout_2.addWidget(self.frequency_bound_lower, 1, 3, 1, 1)
        self.constant_bound_initial = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.constant_bound_initial.setMaximum(0.2)
        self.constant_bound_initial.setSingleStep(0.01)
        self.constant_bound_initial.setObjectName("constant_bound_initial")
        self.gridLayout_2.addWidget(self.constant_bound_initial, 3, 4, 1, 1)
        self.decay_time_bound_upper = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.decay_time_bound_upper.setMaximum(1.0)
        self.decay_time_bound_upper.setSingleStep(0.01)
        self.decay_time_bound_upper.setProperty("value", 1.0)
        self.decay_time_bound_upper.setObjectName("decay_time_bound_upper")
        self.gridLayout_2.addWidget(self.decay_time_bound_upper, 2, 2, 1, 1)
        self.decay_time_bound_lower = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.decay_time_bound_lower.setMaximum(1.0)
        self.decay_time_bound_lower.setSingleStep(0.01)
        self.decay_time_bound_lower.setObjectName("decay_time_bound_lower")
        self.gridLayout_2.addWidget(self.decay_time_bound_lower, 1, 2, 1, 1)
        self.frequency_bound_initial = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.frequency_bound_initial.setMaximum(1000.0)
        self.frequency_bound_initial.setSingleStep(1.0)
        self.frequency_bound_initial.setProperty("value", 300.0)
        self.frequency_bound_initial.setObjectName("frequency_bound_initial")
        self.gridLayout_2.addWidget(self.frequency_bound_initial, 3, 3, 1, 1)
        self.frequency_bound_upper = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.frequency_bound_upper.setMaximum(1000.0)
        self.frequency_bound_upper.setProperty("value", 1000.0)
        self.frequency_bound_upper.setObjectName("frequency_bound_upper")
        self.gridLayout_2.addWidget(self.frequency_bound_upper, 2, 3, 1, 1)
        self.constant_bound_label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constant_bound_label.sizePolicy().hasHeightForWidth())
        self.constant_bound_label.setSizePolicy(sizePolicy)
        self.constant_bound_label.setObjectName("constant_bound_label")
        self.gridLayout_2.addWidget(self.constant_bound_label, 0, 4, 1, 1)
        self.constant_bound_upper = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.constant_bound_upper.setMaximum(0.2)
        self.constant_bound_upper.setSingleStep(0.01)
        self.constant_bound_upper.setProperty("value", 0.01)
        self.constant_bound_upper.setObjectName("constant_bound_upper")
        self.gridLayout_2.addWidget(self.constant_bound_upper, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.vpp_bound_initial = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.vpp_bound_initial.setMaximum(200.0)
        self.vpp_bound_initial.setSingleStep(0.01)
        self.vpp_bound_initial.setProperty("value", 0.1)
        self.vpp_bound_initial.setObjectName("vpp_bound_initial")
        self.gridLayout_2.addWidget(self.vpp_bound_initial, 3, 1, 1, 1)
        self.decay_time_bound_initial = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.decay_time_bound_initial.setMaximum(1.0)
        self.decay_time_bound_initial.setSingleStep(0.01)
        self.decay_time_bound_initial.setProperty("value", 0.4)
        self.decay_time_bound_initial.setObjectName("decay_time_bound_initial")
        self.gridLayout_2.addWidget(self.decay_time_bound_initial, 3, 2, 1, 1)
        self.bounds_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.bounds_checkbox.setGeometry(QtCore.QRect(10, 120, 81, 17))
        self.bounds_checkbox.setChecked(True)
        self.bounds_checkbox.setObjectName("bounds_checkbox")
        self.initial_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.initial_checkbox.setGeometry(QtCore.QRect(100, 120, 91, 17))
        self.initial_checkbox.setChecked(True)
        self.initial_checkbox.setObjectName("initial_checkbox")
        self.fit_button = QtWidgets.QPushButton(self.fitting_tab)
        self.fit_button.setGeometry(QtCore.QRect(650, 408, 101, 51))
        self.fit_button.setObjectName("fit_button")
        self.groupBox_2 = QtWidgets.QGroupBox(self.fitting_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 330, 191, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 171, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vpp_found = QtWidgets.QLineEdit(self.layoutWidget2)
        self.vpp_found.setEnabled(False)
        self.vpp_found.setMaxLength(8)
        self.vpp_found.setObjectName("vpp_found")
        self.gridLayout_3.addWidget(self.vpp_found, 0, 1, 1, 1)
        self.decay_constant_found = QtWidgets.QLineEdit(self.layoutWidget2)
        self.decay_constant_found.setEnabled(False)
        self.decay_constant_found.setMaxLength(8)
        self.decay_constant_found.setObjectName("decay_constant_found")
        self.gridLayout_3.addWidget(self.decay_constant_found, 1, 1, 1, 1)
        self.constant_found_label = QtWidgets.QLabel(self.layoutWidget2)
        self.constant_found_label.setObjectName("constant_found_label")
        self.gridLayout_3.addWidget(self.constant_found_label, 3, 0, 1, 1)
        self.decay_constant_found_label = QtWidgets.QLabel(self.layoutWidget2)
        self.decay_constant_found_label.setObjectName("decay_constant_found_label")
        self.gridLayout_3.addWidget(self.decay_constant_found_label, 1, 0, 1, 1)
        self.constant_found = QtWidgets.QLineEdit(self.layoutWidget2)
        self.constant_found.setEnabled(False)
        self.constant_found.setMaxLength(8)
        self.constant_found.setObjectName("constant_found")
        self.gridLayout_3.addWidget(self.constant_found, 3, 1, 1, 1)
        self.frequency_found = QtWidgets.QLineEdit(self.layoutWidget2)
        self.frequency_found.setEnabled(False)
        self.frequency_found.setMaxLength(8)
        self.frequency_found.setObjectName("frequency_found")
        self.gridLayout_3.addWidget(self.frequency_found, 2, 1, 1, 1)
        self.frequency_found_label = QtWidgets.QLabel(self.layoutWidget2)
        self.frequency_found_label.setObjectName("frequency_found_label")
        self.gridLayout_3.addWidget(self.frequency_found_label, 2, 0, 1, 1)
        self.vpp_found_label = QtWidgets.QLabel(self.layoutWidget2)
        self.vpp_found_label.setObjectName("vpp_found_label")
        self.gridLayout_3.addWidget(self.vpp_found_label, 0, 0, 1, 1)
        self.import_fid_button = QtWidgets.QPushButton(self.fitting_tab)
        self.import_fid_button.setGeometry(QtCore.QRect(650, 340, 101, 51))
        self.import_fid_button.setObjectName("import_fid_button")
        self.main_tabs.addTab(self.fitting_tab, "")
        self.series_acq_tab = QtWidgets.QWidget()
        self.series_acq_tab.setObjectName("series_acq_tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.series_acq_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 190, 197))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.return_pulse_duration_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.return_pulse_duration_label_2.setObjectName("return_pulse_duration_label_2")
        self.gridLayout_4.addWidget(self.return_pulse_duration_label_2, 4, 0, 1, 1)
        self.afid_sampling_period_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.afid_sampling_period_spin.setDecimals(0)
        self.afid_sampling_period_spin.setMinimum(1.0)
        self.afid_sampling_period_spin.setMaximum(100.0)
        self.afid_sampling_period_spin.setSingleStep(1.0)
        self.afid_sampling_period_spin.setProperty("value", 1.0)
        self.afid_sampling_period_spin.setObjectName("afid_sampling_period_spin")
        self.gridLayout_4.addWidget(self.afid_sampling_period_spin, 6, 1, 1, 1)
        self.pulse_amplitude_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.pulse_amplitude_label_2.setObjectName("pulse_amplitude_label_2")
        self.gridLayout_4.addWidget(self.pulse_amplitude_label_2, 3, 0, 1, 1)
        self.apulse_frequency_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.apulse_frequency_spin.setDecimals(3)
        self.apulse_frequency_spin.setMinimum(0.1)
        self.apulse_frequency_spin.setProperty("value", 34.0)
        self.apulse_frequency_spin.setObjectName("apulse_frequency_spin")
        self.gridLayout_4.addWidget(self.apulse_frequency_spin, 0, 1, 1, 1)
        self.afid_n_series_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.afid_n_series_label.setObjectName("afid_n_series_label")
        self.gridLayout_4.addWidget(self.afid_n_series_label, 5, 0, 1, 1)
        self.pulse_density_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.pulse_density_label_2.setObjectName("pulse_density_label_2")
        self.gridLayout_4.addWidget(self.pulse_density_label_2, 2, 0, 1, 1)
        self.pulse_frequency_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.pulse_frequency_label_2.setObjectName("pulse_frequency_label_2")
        self.gridLayout_4.addWidget(self.pulse_frequency_label_2, 0, 0, 1, 1)
        self.afid_sampling_period_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.afid_sampling_period_label.setObjectName("afid_sampling_period_label")
        self.gridLayout_4.addWidget(self.afid_sampling_period_label, 6, 0, 1, 1)
        self.apulse_amplitude_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.apulse_amplitude_spin.setDecimals(1)
        self.apulse_amplitude_spin.setMinimum(0.1)
        self.apulse_amplitude_spin.setMaximum(10.0)
        self.apulse_amplitude_spin.setProperty("value", 0.7)
        self.apulse_amplitude_spin.setObjectName("apulse_amplitude_spin")
        self.gridLayout_4.addWidget(self.apulse_amplitude_spin, 3, 1, 1, 1)
        self.areturn_pulse_duration_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.areturn_pulse_duration_spin.setDecimals(0)
        self.areturn_pulse_duration_spin.setMinimum(1.0)
        self.areturn_pulse_duration_spin.setMaximum(1000.0)
        self.areturn_pulse_duration_spin.setProperty("value", 100.0)
        self.areturn_pulse_duration_spin.setObjectName("areturn_pulse_duration_spin")
        self.gridLayout_4.addWidget(self.areturn_pulse_duration_spin, 4, 1, 1, 1)
        self.afid_n_series_spin = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.afid_n_series_spin.setMinimum(1)
        self.afid_n_series_spin.setMaximum(1000)
        self.afid_n_series_spin.setObjectName("afid_n_series_spin")
        self.gridLayout_4.addWidget(self.afid_n_series_spin, 5, 1, 1, 1)
        self.apulse_duration_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.apulse_duration_spin.setDecimals(1)
        self.apulse_duration_spin.setMinimum(1.0)
        self.apulse_duration_spin.setObjectName("apulse_duration_spin")
        self.gridLayout_4.addWidget(self.apulse_duration_spin, 1, 1, 1, 1)
        self.pulse_duration_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.pulse_duration_label_2.setObjectName("pulse_duration_label_2")
        self.gridLayout_4.addWidget(self.pulse_duration_label_2, 1, 0, 1, 1)
        self.apulse_density_spin = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.apulse_density_spin.setPrefix("")
        self.apulse_density_spin.setMinimum(1)
        self.apulse_density_spin.setMaximum(1000)
        self.apulse_density_spin.setProperty("value", 20)
        self.apulse_density_spin.setObjectName("apulse_density_spin")
        self.gridLayout_4.addWidget(self.apulse_density_spin, 2, 1, 1, 1)
        self.save_directory_label = QtWidgets.QLabel(self.series_acq_tab)
        self.save_directory_label.setGeometry(QtCore.QRect(560, 420, 51, 16))
        self.save_directory_label.setObjectName("save_directory_label")
        self.fid_directory_display = QtWidgets.QLineEdit(self.series_acq_tab)
        self.fid_directory_display.setEnabled(False)
        self.fid_directory_display.setGeometry(QtCore.QRect(610, 420, 112, 19))
        self.fid_directory_display.setObjectName("fid_directory_display")
        self.fid_directory_button = QtWidgets.QToolButton(self.series_acq_tab)
        self.fid_directory_button.setGeometry(QtCore.QRect(730, 420, 25, 19))
        self.fid_directory_button.setObjectName("fid_directory_button")
        self.afid_start_button = QtWidgets.QPushButton(self.series_acq_tab)
        self.afid_start_button.setGeometry(QtCore.QRect(564, 450, 191, 23))
        self.afid_start_button.setObjectName("afid_start_button")
        self.fid_series_acq_progress = QtWidgets.QProgressBar(self.series_acq_tab)
        self.fid_series_acq_progress.setGeometry(QtCore.QRect(560, 380, 191, 23))
        self.fid_series_acq_progress.setProperty("value", 0)
        self.fid_series_acq_progress.setObjectName("fid_series_acq_progress")
        self.main_tabs.addTab(self.series_acq_tab, "")
        self.series_fitting_tab = QtWidgets.QWidget()
        self.series_fitting_tab.setObjectName("series_fitting_tab")
        self.layoutWidget3 = QtWidgets.QWidget(self.series_fitting_tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 751, 461))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.series_fitting_group = QtWidgets.QGroupBox(self.layoutWidget3)
        self.series_fitting_group.setObjectName("series_fitting_group")
        self.fid_series_fitting_plot = QtWidgets.QWidget(self.series_fitting_group)
        self.fid_series_fitting_plot.setGeometry(QtCore.QRect(190, 20, 541, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fid_series_fitting_plot.sizePolicy().hasHeightForWidth())
        self.fid_series_fitting_plot.setSizePolicy(sizePolicy)
        self.fid_series_fitting_plot.setObjectName("fid_series_fitting_plot")
        self.layoutWidget4 = QtWidgets.QWidget(self.series_fitting_group)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 171, 91))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fit_fid_series_button = QtWidgets.QPushButton(self.layoutWidget4)
        self.fit_fid_series_button.setObjectName("fit_fid_series_button")
        self.gridLayout_5.addWidget(self.fit_fid_series_button, 2, 0, 1, 2)
        self.afid_sampling_period_label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.afid_sampling_period_label_2.setObjectName("afid_sampling_period_label_2")
        self.gridLayout_5.addWidget(self.afid_sampling_period_label_2, 1, 0, 1, 1)
        self.afid_sampling_period_spin_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.afid_sampling_period_spin_2.setDecimals(0)
        self.afid_sampling_period_spin_2.setMinimum(1.0)
        self.afid_sampling_period_spin_2.setMaximum(100.0)
        self.afid_sampling_period_spin_2.setSingleStep(1.0)
        self.afid_sampling_period_spin_2.setProperty("value", 1.0)
        self.afid_sampling_period_spin_2.setObjectName("afid_sampling_period_spin_2")
        self.gridLayout_5.addWidget(self.afid_sampling_period_spin_2, 1, 1, 1, 1)
        self.afid_n_series_spin_2 = QtWidgets.QSpinBox(self.layoutWidget4)
        self.afid_n_series_spin_2.setMinimum(1)
        self.afid_n_series_spin_2.setMaximum(1000)
        self.afid_n_series_spin_2.setObjectName("afid_n_series_spin_2")
        self.gridLayout_5.addWidget(self.afid_n_series_spin_2, 0, 1, 1, 1)
        self.afid_n_series_label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.afid_n_series_label_2.setObjectName("afid_n_series_label_2")
        self.gridLayout_5.addWidget(self.afid_n_series_label_2, 0, 0, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.series_fitting_group)
        self.layoutWidget5.setGeometry(QtCore.QRect(8, 160, 171, 51))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.export_fid_series_button = QtWidgets.QPushButton(self.layoutWidget5)
        self.export_fid_series_button.setObjectName("export_fid_series_button")
        self.gridLayout_7.addWidget(self.export_fid_series_button, 0, 0, 1, 3)
        self.fid_directory_label_2 = QtWidgets.QLabel(self.layoutWidget5)
        self.fid_directory_label_2.setObjectName("fid_directory_label_2")
        self.gridLayout_7.addWidget(self.fid_directory_label_2, 1, 0, 1, 1)
        self.fid_directory_display_2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.fid_directory_display_2.setEnabled(False)
        self.fid_directory_display_2.setObjectName("fid_directory_display_2")
        self.gridLayout_7.addWidget(self.fid_directory_display_2, 1, 1, 1, 1)
        self.fid_directory_button_2 = QtWidgets.QToolButton(self.layoutWidget5)
        self.fid_directory_button_2.setObjectName("fid_directory_button_2")
        self.gridLayout_7.addWidget(self.fid_directory_button_2, 1, 2, 1, 1)
        self.layoutWidget.raise_()
        self.fid_series_fitting_plot.raise_()
        self.layoutWidget.raise_()
        self.verticalLayout.addWidget(self.series_fitting_group)
        self.multiple_plotting_group = QtWidgets.QGroupBox(self.layoutWidget3)
        self.multiple_plotting_group.setObjectName("multiple_plotting_group")
        self.fid_multiple_plot = QtWidgets.QWidget(self.multiple_plotting_group)
        self.fid_multiple_plot.setGeometry(QtCore.QRect(190, 20, 541, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fid_multiple_plot.sizePolicy().hasHeightForWidth())
        self.fid_multiple_plot.setSizePolicy(sizePolicy)
        self.fid_multiple_plot.setObjectName("fid_multiple_plot")
        self.layoutWidget_3 = QtWidgets.QWidget(self.multiple_plotting_group)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 171, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.multiple_fids_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.multiple_fids_label.setObjectName("multiple_fids_label")
        self.gridLayout_8.addWidget(self.multiple_fids_label, 0, 0, 1, 1)
        self.multiple_fids_input = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.multiple_fids_input.setObjectName("multiple_fids_input")
        self.gridLayout_8.addWidget(self.multiple_fids_input, 0, 1, 1, 1)
        self.plot_multiple_fid_button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.plot_multiple_fid_button.setObjectName("plot_multiple_fid_button")
        self.gridLayout_8.addWidget(self.plot_multiple_fid_button, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.multiple_plotting_group)
        self.main_tabs.addTab(self.series_fitting_tab, "")
        self.afp_tab = QtWidgets.QWidget()
        self.afp_tab.setObjectName("afp_tab")
        self.afp_flip_button = QtWidgets.QPushButton(self.afp_tab)
        self.afp_flip_button.setGeometry(QtCore.QRect(530, 310, 231, 131))
        self.afp_flip_button.setObjectName("afp_flip_button")
        self.widget = QtWidgets.QWidget(self.afp_tab)
        self.widget.setGeometry(QtCore.QRect(530, 450, 234, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.curr_state_edit = QtWidgets.QLineEdit(self.widget)
        self.curr_state_edit.setEnabled(False)
        self.curr_state_edit.setReadOnly(True)
        self.curr_state_edit.setObjectName("curr_state_edit")
        self.horizontalLayout.addWidget(self.curr_state_edit)
        self.poll_state_button = QtWidgets.QPushButton(self.widget)
        self.poll_state_button.setObjectName("poll_state_button")
        self.horizontalLayout.addWidget(self.poll_state_button)
        self.widget1 = QtWidgets.QWidget(self.afp_tab)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 158, 74))
        self.widget1.setObjectName("widget1")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frequency_lower_label = QtWidgets.QLabel(self.widget1)
        self.frequency_lower_label.setObjectName("frequency_lower_label")
        self.gridLayout_9.addWidget(self.frequency_lower_label, 0, 0, 1, 1)
        self.frequency_lower_spin = QtWidgets.QDoubleSpinBox(self.widget1)
        self.frequency_lower_spin.setDecimals(3)
        self.frequency_lower_spin.setMinimum(1.0)
        self.frequency_lower_spin.setMaximum(100.0)
        self.frequency_lower_spin.setProperty("value", 30.0)
        self.frequency_lower_spin.setObjectName("frequency_lower_spin")
        self.gridLayout_9.addWidget(self.frequency_lower_spin, 0, 1, 1, 1)
        self.frequency_higher_label = QtWidgets.QLabel(self.widget1)
        self.frequency_higher_label.setObjectName("frequency_higher_label")
        self.gridLayout_9.addWidget(self.frequency_higher_label, 1, 0, 1, 1)
        self.frequency_higher_spin = QtWidgets.QDoubleSpinBox(self.widget1)
        self.frequency_higher_spin.setDecimals(3)
        self.frequency_higher_spin.setMinimum(1.0)
        self.frequency_higher_spin.setMaximum(100.0)
        self.frequency_higher_spin.setProperty("value", 30.0)
        self.frequency_higher_spin.setObjectName("frequency_higher_spin")
        self.gridLayout_9.addWidget(self.frequency_higher_spin, 1, 1, 1, 1)
        self.pulse_length_label = QtWidgets.QLabel(self.widget1)
        self.pulse_length_label.setObjectName("pulse_length_label")
        self.gridLayout_9.addWidget(self.pulse_length_label, 2, 0, 1, 1)
        self.pulse_length_spin = QtWidgets.QDoubleSpinBox(self.widget1)
        self.pulse_length_spin.setDecimals(2)
        self.pulse_length_spin.setMinimum(0.01)
        self.pulse_length_spin.setMaximum(2.0)
        self.pulse_length_spin.setSingleStep(0.01)
        self.pulse_length_spin.setProperty("value", 0.5)
        self.pulse_length_spin.setObjectName("pulse_length_spin")
        self.gridLayout_9.addWidget(self.pulse_length_spin, 2, 1, 1, 1)
        self.main_tabs.addTab(self.afp_tab, "")
        self.pref_tab = QtWidgets.QWidget()
        self.pref_tab.setObjectName("pref_tab")
        self.layoutWidget6 = QtWidgets.QWidget(self.pref_tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 10, 241, 74))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.output_terminal_combo = QtWidgets.QComboBox(self.layoutWidget6)
        self.output_terminal_combo.setObjectName("output_terminal_combo")
        self.gridLayout_6.addWidget(self.output_terminal_combo, 0, 1, 1, 1)
        self.output_terminal_label = QtWidgets.QLabel(self.layoutWidget6)
        self.output_terminal_label.setObjectName("output_terminal_label")
        self.gridLayout_6.addWidget(self.output_terminal_label, 0, 0, 1, 1)
        self.input_terminal_label = QtWidgets.QLabel(self.layoutWidget6)
        self.input_terminal_label.setObjectName("input_terminal_label")
        self.gridLayout_6.addWidget(self.input_terminal_label, 1, 0, 1, 1)
        self.input_terminal_combo = QtWidgets.QComboBox(self.layoutWidget6)
        self.input_terminal_combo.setObjectName("input_terminal_combo")
        self.gridLayout_6.addWidget(self.input_terminal_combo, 1, 1, 1, 1)
        self.afp_terminal_label = QtWidgets.QLabel(self.layoutWidget6)
        self.afp_terminal_label.setObjectName("afp_terminal_label")
        self.gridLayout_6.addWidget(self.afp_terminal_label, 2, 0, 1, 1)
        self.afp_terminal_combo = QtWidgets.QComboBox(self.layoutWidget6)
        self.afp_terminal_combo.setObjectName("afp_terminal_combo")
        self.afp_terminal_combo.addItem("")
        self.afp_terminal_combo.addItem("")
        self.gridLayout_6.addWidget(self.afp_terminal_combo, 2, 1, 1, 1)
        self.main_tabs.addTab(self.pref_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NMR Control"))
        self.export_fid_button.setText(_translate("MainWindow", "Export FID"))
        self.pulse_frequency_label.setText(_translate("MainWindow", "Pulse Freq."))
        self.pulse_frequency_spin.setSuffix(_translate("MainWindow", " kHz"))
        self.pulse_duration_label.setText(_translate("MainWindow", "Pulse Duration"))
        self.pulse_duration_spin.setSuffix(_translate("MainWindow", " ms"))
        self.pulse_density_label.setText(_translate("MainWindow", "Pulse Density"))
        self.pulse_density_spin.setSuffix(_translate("MainWindow", " per period"))
        self.pulse_amplitude_label.setText(_translate("MainWindow", "Pulse Amplitude"))
        self.pulse_amplitude_spin.setSuffix(_translate("MainWindow", " V"))
        self.pulse_button.setText(_translate("MainWindow", "Pulse"))
        self.return_pulse_duration_spin.setSuffix(_translate("MainWindow", " ms"))
        self.return_pulse_duration_label.setText(_translate("MainWindow", "Read Duration"))
        self.decimation_factor_label.setText(_translate("MainWindow", "Decimation Factor"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.nmr_signaller_tab), _translate("MainWindow", "Single FID Acquisition"))
        self.groupBox.setTitle(_translate("MainWindow", "Fitting Bounds"))
        self.frequency_bound_label.setText(_translate("MainWindow", "f"))
        self.vpp_bound_upper.setSuffix(_translate("MainWindow", " mV"))
        self.upper_bounds_label.setText(_translate("MainWindow", "Upper"))
        self.lower_bounds_label.setText(_translate("MainWindow", "Lower"))
        self.vpp_bound_label.setText(_translate("MainWindow", "V_pp"))
        self.vpp_bound_lower.setSuffix(_translate("MainWindow", " mV"))
        self.decay_time_bound_label.setText(_translate("MainWindow", "t_0"))
        self.frequency_bound_lower.setSuffix(_translate("MainWindow", " Hz"))
        self.decay_time_bound_upper.setSuffix(_translate("MainWindow", " s"))
        self.decay_time_bound_lower.setSuffix(_translate("MainWindow", " s"))
        self.frequency_bound_initial.setSuffix(_translate("MainWindow", " Hz"))
        self.frequency_bound_upper.setSuffix(_translate("MainWindow", " Hz"))
        self.constant_bound_label.setText(_translate("MainWindow", "c"))
        self.label.setText(_translate("MainWindow", "Initial"))
        self.vpp_bound_initial.setSuffix(_translate("MainWindow", " mV"))
        self.decay_time_bound_initial.setSuffix(_translate("MainWindow", " s"))
        self.bounds_checkbox.setText(_translate("MainWindow", "Use bounds"))
        self.initial_checkbox.setText(_translate("MainWindow", "Use initial val"))
        self.fit_button.setText(_translate("MainWindow", "Fit"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fitted Parameters"))
        self.constant_found_label.setText(_translate("MainWindow", "Constant"))
        self.decay_constant_found_label.setText(_translate("MainWindow", "Decay Constant"))
        self.frequency_found_label.setText(_translate("MainWindow", "Osc. Frequency"))
        self.vpp_found_label.setText(_translate("MainWindow", "P2P Voltage"))
        self.import_fid_button.setText(_translate("MainWindow", "Import FID"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.fitting_tab), _translate("MainWindow", "Single FID Fitting"))
        self.return_pulse_duration_label_2.setText(_translate("MainWindow", "Read Duration"))
        self.afid_sampling_period_spin.setSuffix(_translate("MainWindow", " mins"))
        self.pulse_amplitude_label_2.setText(_translate("MainWindow", "Pulse Amplitude"))
        self.apulse_frequency_spin.setSuffix(_translate("MainWindow", " kHz"))
        self.afid_n_series_label.setText(_translate("MainWindow", "N Series"))
        self.pulse_density_label_2.setText(_translate("MainWindow", "Pulse Density"))
        self.pulse_frequency_label_2.setText(_translate("MainWindow", "Pulse Freq."))
        self.afid_sampling_period_label.setText(_translate("MainWindow", "Sampling Period"))
        self.apulse_amplitude_spin.setSuffix(_translate("MainWindow", " V"))
        self.areturn_pulse_duration_spin.setSuffix(_translate("MainWindow", " ms"))
        self.apulse_duration_spin.setSuffix(_translate("MainWindow", " ms"))
        self.pulse_duration_label_2.setText(_translate("MainWindow", "Pulse Duration"))
        self.apulse_density_spin.setSuffix(_translate("MainWindow", " per pulse"))
        self.save_directory_label.setText(_translate("MainWindow", "Directory"))
        self.fid_directory_button.setText(_translate("MainWindow", "..."))
        self.afid_start_button.setText(_translate("MainWindow", "Start"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.series_acq_tab), _translate("MainWindow", "Automatic FID Series Acquisition"))
        self.series_fitting_group.setTitle(_translate("MainWindow", "Series Fitting"))
        self.fit_fid_series_button.setText(_translate("MainWindow", "Fit"))
        self.afid_sampling_period_label_2.setText(_translate("MainWindow", "Sampling Period"))
        self.afid_sampling_period_spin_2.setSuffix(_translate("MainWindow", " mins"))
        self.afid_n_series_label_2.setText(_translate("MainWindow", "N Series"))
        self.export_fid_series_button.setText(_translate("MainWindow", "Export"))
        self.fid_directory_label_2.setText(_translate("MainWindow", "Directory"))
        self.fid_directory_button_2.setText(_translate("MainWindow", "..."))
        self.multiple_plotting_group.setTitle(_translate("MainWindow", "Multiple Plotting"))
        self.multiple_fids_label.setText(_translate("MainWindow", "FIDs"))
        self.plot_multiple_fid_button.setText(_translate("MainWindow", "Plot"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.series_fitting_tab), _translate("MainWindow", "FID Series Fitting"))
        self.afp_flip_button.setText(_translate("MainWindow", "Flip"))
        self.poll_state_button.setText(_translate("MainWindow", "Poll Current State"))
        self.frequency_lower_label.setText(_translate("MainWindow", "Frequency Lo"))
        self.frequency_lower_spin.setSuffix(_translate("MainWindow", " kHz"))
        self.frequency_higher_label.setText(_translate("MainWindow", "Frequency Hi"))
        self.frequency_higher_spin.setSuffix(_translate("MainWindow", " kHz"))
        self.pulse_length_label.setText(_translate("MainWindow", "Pulse Length"))
        self.pulse_length_spin.setSuffix(_translate("MainWindow", " s"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.afp_tab), _translate("MainWindow", "AFP"))
        self.output_terminal_label.setText(_translate("MainWindow", "NMR Coil Output"))
        self.input_terminal_label.setText(_translate("MainWindow", "NMR Coil Input"))
        self.afp_terminal_label.setText(_translate("MainWindow", "AFP Input"))
        self.afp_terminal_combo.setItemText(0, _translate("MainWindow", "Dev1/ao1"))
        self.afp_terminal_combo.setItemText(1, _translate("MainWindow", "Dev1/ao0"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.pref_tab), _translate("MainWindow", "Preferences"))

